In [39]:
import numpy as np
import yfinance as yf
import pandas as pd

In [40]:
tickers = [
    "SPY",   # S&P 500 ETF
    "AAPL",  # Apple
    "NVDA",  # Nvidia
    "MSFT",  # Microsoft
    "JPM",   # JPMorgan Chase
    "BAC",   # Bank of America
    "SHEL",  # Shell
    "XOM",   # Exxon Mobil
    "GLD",   # SPDR Gold Shares
    "BZ=F",  # Brent crude oil futures
    "NG=F"   # Natural gas (Henry Hub) futures
]

START_DATE = "2010-01-01"
END_DATE = "2026-09-14"

In [41]:
data = yf.download(
    tickers,
    start=START_DATE,
    end=END_DATE,
    interval="1d",
    auto_adjust=True,
    progress=False
)

In [42]:
data

Price            Close                                                 \
Ticker            AAPL        BAC        BZ=F         GLD         JPM
Date
2010-01-04    6.400960  11.977119   80.120003  109.800003   28.152386
2010-01-05    6.412027  12.366443   80.589996  109.699997   28.697697
2010-01-06    6.310033  12.511473   81.889999  111.510002   28.855366
2010-01-07    6.298369  12.923693   81.510002  110.820000   29.426964
2010-01-08    6.340246  12.809185   81.370003  111.370003   29.354683
...                ...        ...         ...         ...         ...
2026-09-04  319.970001  62.680000   96.279999  406.769989  358.640015
2026-09-08  316.220001  62.389999   97.919998  399.720001  353.510010
2026-09-09  315.339996  62.669998  101.209999  403.350006  354.709991
2026-09-10  326.570007  62.560001  107.629997  396.359985  353.559998
2026-09-11  332.269989  62.689999  104.610001  398.769989  356.230011

Price                                                             ...  \
Ticker            MSFT   NG=F        NVDA       SHEL         SPY  ...
Date                                                              ...
2010-01-04   22.984238  5.884    0.422817  26.799492   84.368950  ...
2010-01-05   22.991659  5.637    0.428992  26.829590   84.592316  ...
2010-01-06   22.850571  6.009    0.431736  26.610382   84.651855  ...
2010-01-07   22.612926  5.806    0.423275  26.481436   85.009201  ...
2010-01-08   22.768871  5.749    0.424189  26.442745   85.292107  ...
...                ...    ...         ...        ...         ...  ...
2026-09-04  499.700012  2.975  230.102524  92.949997  768.282227  ...
2026-09-08  493.950012  2.916  225.477692  95.320000  764.062683  ...
2026-09-09  491.649994  2.822  223.419998  95.599998  760.511536  ...
2026-09-10  492.440002  2.834  218.360001  95.959999  755.952820  ...
2026-09-11  495.630005  2.831  218.289993  96.769997  762.396790  ...

Price            Volume                                               \
Ticker              BAC     BZ=F         GLD         JPM        MSFT
Date
2010-01-04  180845200.0     97.0  16224100.0  35460500.0  38409100.0
2010-01-05  209521300.0     97.0  14213100.0  41208300.0  49749600.0
2010-01-06  205257900.0      7.0  24981900.0  27729000.0  58182400.0
2010-01-07  320868400.0      7.0  13609800.0  44864700.0  50559700.0
2010-01-08  220104700.0      7.0  15894600.0  33110100.0  51197400.0
...                 ...      ...         ...         ...         ...
2026-09-04   26587200.0  35106.0   9813200.0   4873500.0  18101800.0
2026-09-08   28338000.0  71135.0   8992200.0   5631400.0  18882300.0
2026-09-09   36015200.0  51567.0   8188400.0   6318200.0  12889600.0
2026-09-10   29359100.0  72538.0  10202900.0   4184200.0  16038800.0
2026-09-11   28873700.0  61285.0  10963000.0   5354600.0  14510500.0

Price
Ticker          NG=F         NVDA       SHEL          SPY         XOM
Date
2010-01-04   78858.0  800204000.0  1643003.0  118944600.0  27809100.0
2010-01-05   99492.0  728648000.0  1718458.0  111579900.0  30174700.0
2010-01-06  140611.0  649168000.0  3040554.0  116074400.0  35044700.0
2010-01-07  135113.0  547792000.0  1033089.0  131091100.0  27192100.0
2010-01-08  101153.0  478168000.0  1438017.0  126402800.0  24891800.0
...              ...          ...        ...          ...         ...
2026-09-04  150051.0  135352400.0  6849003.0   34054200.0  16206400.0
2026-09-08  248447.0  122965600.0  7425065.0   44746100.0  12607700.0
2026-09-09  178990.0   82955500.0  8384823.0   32812400.0  13124000.0
2026-09-10  174179.0  105768000.0  6483274.0   42740400.0  16615300.0
2026-09-11  128318.0   89060100.0  5251076.0   45512700.0  11362400.0

[4201 rows x 55 columns]

In [43]:
data = data["Close"].sort_index()

In [44]:
data.tail()

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,768.282227,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,764.062683,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,760.511536,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,755.952820,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,762.396790,165.990005

In [45]:
data

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2010-01-04,6.400960,11.977119,80.120003,109.800003,28.152386,22.984238,5.884,0.422817,26.799492,84.368950,37.136803
2010-01-05,6.412027,12.366443,80.589996,109.699997,28.697697,22.991659,5.637,0.428992,26.829590,84.592316,37.281807
2010-01-06,6.310033,12.511473,81.889999,111.510002,28.855366,22.850571,6.009,0.431736,26.610382,84.651855,37.604050
2010-01-07,6.298369,12.923693,81.510002,110.820000,29.426964,22.612926,5.806,0.423275,26.481436,85.009201,37.485889
2010-01-08,6.340246,12.809185,81.370003,111.370003,29.354683,22.768871,5.749,0.424189,26.442745,85.292107,37.335510
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,768.282227,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,764.062683,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,760.511536,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,755.952820,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,762.396790,165.990005

In [46]:
# date orrdre croissant
data.tail(10)

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2026-08-28,319.700012,62.003654,89.309998,408.890015,357.619995,513.530029,2.888,217.306839,90.910004,767.444275,156.710007
2026-08-31,316.850006,61.625580,90.489998,408.420013,356.019989,507.290009,2.935,220.533234,91.449997,765.149963,160.949997
2026-09-01,325.130005,61.675331,94.650002,396.750000,354.950012,501.019989,2.904,217.196976,93.510002,759.893066,164.550003
2026-09-02,324.959991,62.282230,95.629997,402.779999,356.220001,496.820007,2.956,224.159180,92.800003,763.264648,164.149994
2026-09-03,328.209991,62.719997,95.519997,410.220001,362.059998,510.119995,2.913,228.194656,92.330002,771.254822,162.210007
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,768.282227,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,764.062683,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,760.511536,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,755.952820,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,762.396790,165.990005

In [47]:
data.rename(columns={
    
    "SPY": "S&P 500",
    "AAPL": "Apple",
    "NVDA": "Nvidia",
    "MSFT": "Microsoft",
    "JPM": "JPMorgan",
    "BAC": "Bank of America",
    "SHEL": "Shell",
    "XOM": "Exxon Mobil",
    "GLD": "Gold",
    "BZ=F": "Oil",
    "NG=F": "Gas"
    
},inplace = True)

In [48]:
data.head(10)

Ticker,Apple,Bank of America,Oil,Gold,JPMorgan,Microsoft,Gas,Nvidia,Shell,S&P 500,Exxon Mobil
Date,,,,,,,,,,,
2010-01-04,6.400960,11.977119,80.120003,109.800003,28.152386,22.984238,5.884,0.422817,26.799492,84.368950,37.136803
2010-01-05,6.412027,12.366443,80.589996,109.699997,28.697697,22.991659,5.637,0.428992,26.829590,84.592316,37.281807
2010-01-06,6.310033,12.511473,81.889999,111.510002,28.855366,22.850571,6.009,0.431736,26.610382,84.651855,37.604050
2010-01-07,6.298369,12.923693,81.510002,110.820000,29.426964,22.612926,5.806,0.423275,26.481436,85.009201,37.485889
2010-01-08,6.340246,12.809185,81.370003,111.370003,29.354683,22.768871,5.749,0.424189,26.442745,85.292107,37.335510
2010-01-11,6.284312,12.923693,80.970001,112.849998,29.256138,22.479248,5.454,0.418244,26.855368,85.411224,37.754410
2010-01-12,6.212828,12.488576,79.300003,110.489998,28.572853,22.330730,5.591,0.404066,26.249323,84.614655,37.566448
2010-01-13,6.300463,12.687054,78.309998,111.540001,29.072176,22.538666,5.733,0.409554,26.266523,85.329338,37.416069
2010-01-14,6.263974,12.839719,77.820000,112.029999,29.361261,22.991659,5.588,0.403151,26.202030,85.560104,37.421463
2010-01-15,6.159291,12.412238,77.110001,110.860001,28.697697,22.917404,5.691,0.391260,26.008621,84.599739,37.115330

In [49]:
# savoir le nombre de NaN
data.isna().sum()

Ticker
Apple               3
Bank of America     3
Oil                34
Gold                3
JPMorgan            3
Microsoft           3
Gas                 2
Nvidia              3
Shell               3
S&P 500             3
Exxon Mobil         3
dtype: int64

In [50]:
data.dropna(inplace=True)
data.isna().sum()

Ticker
Apple              0
Bank of America    0
Oil                0
Gold               0
JPMorgan           0
Microsoft          0
Gas                0
Nvidia             0
Shell              0
S&P 500            0
Exxon Mobil        0
dtype: int64

In [51]:
data

Ticker,Apple,Bank of America,Oil,Gold,JPMorgan,Microsoft,Gas,Nvidia,Shell,S&P 500,Exxon Mobil
Date,,,,,,,,,,,
2010-01-04,6.400960,11.977119,80.120003,109.800003,28.152386,22.984238,5.884,0.422817,26.799492,84.368950,37.136803
2010-01-05,6.412027,12.366443,80.589996,109.699997,28.697697,22.991659,5.637,0.428992,26.829590,84.592316,37.281807
2010-01-06,6.310033,12.511473,81.889999,111.510002,28.855366,22.850571,6.009,0.431736,26.610382,84.651855,37.604050
2010-01-07,6.298369,12.923693,81.510002,110.820000,29.426964,22.612926,5.806,0.423275,26.481436,85.009201,37.485889
2010-01-08,6.340246,12.809185,81.370003,111.370003,29.354683,22.768871,5.749,0.424189,26.442745,85.292107,37.335510
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,768.282227,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,764.062683,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,760.511536,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,755.952820,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,762.396790,165.990005

In [52]:
data.columns

Index(['Apple', 'Bank of America', 'Oil', 'Gold', 'JPMorgan', 'Microsoft',
       'Gas', 'Nvidia', 'Shell', 'S&P 500', 'Exxon Mobil'],
      dtype='object', name='Ticker')

In [53]:
column = ["S&P 500", "Nvidia", "Apple", "Microsoft", "JPMorgan", "Bank of America", "Exxon Mobil", "Shell", "Gold", "Oil", "Gas" ]
data = data[column]

In [54]:
data

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-01-04,84.368950,0.422817,6.400960,22.984238,28.152386,11.977119,37.136803,26.799492,109.800003,80.120003,5.884
2010-01-05,84.592316,0.428992,6.412027,22.991659,28.697697,12.366443,37.281807,26.829590,109.699997,80.589996,5.637
2010-01-06,84.651855,0.431736,6.310033,22.850571,28.855366,12.511473,37.604050,26.610382,111.510002,81.889999,6.009
2010-01-07,85.009201,0.423275,6.298369,22.612926,29.426964,12.923693,37.485889,26.481436,110.820000,81.510002,5.806
2010-01-08,85.292107,0.424189,6.340246,22.768871,29.354683,12.809185,37.335510,26.442745,111.370003,81.370003,5.749
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,768.282227,230.102524,319.970001,499.700012,358.640015,62.680000,159.470001,92.949997,406.769989,96.279999,2.975
2026-09-08,764.062683,225.477692,316.220001,493.950012,353.510010,62.389999,160.660004,95.320000,399.720001,97.919998,2.916
2026-09-09,760.511536,223.419998,315.339996,491.649994,354.709991,62.669998,164.229996,95.599998,403.350006,101.209999,2.822
2026-09-10,755.952820,218.360001,326.570007,492.440002,353.559998,62.560001,165.229996,95.959999,396.359985,107.629997,2.834
2026-09-11,762.396790,218.289993,332.269989,495.630005,356.230011,62.689999,165.990005,96.769997,398.769989,104.610001,2.831

In [55]:
data.iloc[-1]

Ticker
S&P 500            762.396790
Nvidia             218.289993
Apple              332.269989
Microsoft          495.630005
JPMorgan           356.230011
Bank of America     62.689999
Exxon Mobil        165.990005
Shell               96.769997
Gold               398.769989
Oil                104.610001
Gas                  2.831000
Name: 2026-09-11 00:00:00, dtype: float64

In [56]:
# dataframe avec les rendemtns
returns = data.pct_change().dropna()
returns

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-01-05,0.002647,0.014603,0.001729,0.000323,0.019370,0.032506,0.003905,0.001123,-0.000911,0.005866,-0.041978
2010-01-06,0.000704,0.006397,-0.015907,-0.006137,0.005494,0.011728,0.008643,-0.008170,0.016500,0.016131,0.065993
2010-01-07,0.004221,-0.019598,-0.001848,-0.010400,0.019809,0.032947,-0.003142,-0.004846,-0.006188,-0.004640,-0.033783
2010-01-08,0.003328,0.002161,0.006649,0.006896,-0.002456,-0.008860,-0.004012,-0.001461,0.004963,-0.001718,-0.009817
2010-01-11,0.001397,-0.014016,-0.008822,-0.012720,-0.003357,0.008939,0.011220,0.015604,0.013289,-0.004916,-0.051313
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,-0.003854,0.008361,-0.025106,-0.020427,-0.009446,-0.000638,-0.016892,0.006715,-0.008410,0.007956,0.021284
2026-09-08,-0.005492,-0.020099,-0.011720,-0.011507,-0.014304,-0.004627,0.007462,0.025498,-0.017332,0.017034,-0.019832
2026-09-09,-0.004648,-0.009126,-0.002783,-0.004656,0.003394,0.004488,0.022221,0.002937,0.009081,0.033599,-0.032236
2026-09-10,-0.005994,-0.022648,0.035612,0.001607,-0.003242,-0.001755,0.006089,0.003766,-0.017330,0.063432,0.004252
2026-09-11,0.008524,-0.000321,0.017454,0.006478,0.007552,0.002078,0.004600,0.008441,0.006080,-0.028059,-0.001059

In [57]:
# on ne garde que les jours ou rendement S&P inf à 3%
crash_days = returns.loc[returns["S&P 500"]<=-0.03]
crash_days

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-02-04,-0.030866,-0.058058,-0.036039,-0.027593,-0.048151,-0.050226,-0.028228,-0.040719,-0.039834,-0.049921,-0.000554
2010-05-06,-0.033213,-0.020690,-0.038049,-0.029146,-0.042693,-0.071306,-0.034457,-0.034561,0.029542,-0.033652,-0.015535
2010-05-20,-0.037759,-0.023511,-0.042602,-0.040014,-0.039360,-0.061925,-0.033947,-0.017351,-0.006774,-0.025105,-0.012506
2010-06-04,-0.035137,-0.047244,-0.027212,-0.039836,-0.037852,-0.029096,-0.032976,-0.042175,0.010427,-0.044026,0.022814
2010-06-29,-0.030875,-0.055856,-0.045210,-0.041136,-0.038402,-0.043963,-0.020181,-0.031593,0.001487,-0.027710,-0.035828
2011-08-04,-0.046842,-0.095206,-0.038719,-0.036404,-0.049624,-0.074423,-0.049923,-0.070523,-0.005264,-0.052813,-0.036430
2011-08-08,-0.065123,-0.078764,-0.054627,-0.046729,-0.094149,-0.203182,-0.061882,-0.068168,0.033199,-0.051477,-0.001522
2011-08-10,-0.044177,-0.045630,-0.027593,-0.053949,-0.055769,-0.109210,-0.044120,-0.040357,0.035407,0.040070,0.002253
2011-08-18,-0.043118,-0.067916,-0.037825,-0.022970,-0.037736,-0.060322,-0.043420,-0.036077,0.018920,-0.032640,-0.010425
2011-09-22,-0.032324,-0.066345,-0.025040,-0.035783,-0.035267,-0.050157,-0.037933,-0.023753,-0.026154,-0.044128,-0.006702
2011-11-09,-0.036909,-0.050398,-0.026955,-0.035346,-0.070817,-0.056662,-0.029714,-0.049910,-0.008413,-0.023391,-0.024833
2015-08-21,-0.030102,-0.031137,-0.061163,-0.056724,-0.035487,-0.037082,-0.032721,-0.032294,0.006248,-0.024882,-0.028675
2015-08-24,-0.042107,-0.035398,-0.024962,-0.032273,-0.052673,-0.050310,-0.047276,-0.051678,-0.005399,-0.060933,-0.009716
2016-06-24,-0.035909,-0.056919,-0.028096,-0.040069,-0.069477,-0.074074,-0.026252,-0.064347,0.049038,-0.049106,-0.013343
2018-02-05,-0.041823,-0.084875,-0.024985,-0.041185,-0.047952,-0.052895,-0.056902,-0.041010,0.002532,-0.013998,-0.034786
2018-02-08,-0.037509,-0.049300,-0.027516,-0.051334,-0.044210,-0.048320,-0.011307,-0.022116,0.001523,-0.010685,-0.001850
2018-10-10,-0.031663,-0.074753,-0.046326,-0.054338,-0.026633,-0.024683,-0.023003,-0.020202,0.002487,-0.022471,0.005511
2018-10-24,-0.030298,-0.097938,-0.034302,-0.053469,-0.018622,-0.030718,-0.027805,-0.027888,0.002320,-0.003532,-0.014321
2018-12-04,-0.032402,-0.076041,-0.043989,-0.031849,-0.044637,-0.054310,-0.022039,-0.018597,0.006099,0.006322,0.027195
2019-08-05,-0.030073,-0.064520,-0.052348,-0.034259,-0.029753,-0.044248,-0.020488,-0.022941,0.013982,-0.033608,-0.024045
2020-02-24,-0.033165,-0.070697,-0.047500,-0.043115,-0.026876,-0.047439,-0.046846,-0.038438,0.008985,-0.037607,-0.040945
2020-02-25,-0.030302,-0.041094,-0.033872,-0.016502,-0.044643,-0.050412,-0.038325,-0.029188,-0.017874,-0.023979,0.010947
2020-02-27,-0.044912,-0.055666,-0.065368,-0.070459,-0.041614,-0.048972,-0.060177,-0.039563,0.000195,-0.023395,-0.037891
2020-03-05,-0.033242,-0.039436,-0.032437,-0.025095,-0.049062,-0.050691,-0.044067,-0.034658,0.021601,-0.022296,-0.030104
2020-03-09,-0.078094,-0.077432,-0.079092,-0.067772,-0.135455,-0.147024,-0.122248,-0.171722,0.001650,-0.240998,0.040984
2020-03-11,-0.048749,-0.055960,-0.034730,-0.045302,-0.047070,-0.039813,-0.032942,-0.066829,-0.003560,-0.038420,-0.029959
2020-03-12,-0.095677,-0.122368,-0.098755,-0.094838,-0.082430,-0.095280,-0.114340,-0.149609,-0.039888,-0.071808,-0.019702
2020-03-16,-0.109424,-0.184521,-0.128647,-0.147391,-0.149649,-0.153973,-0.095226,-0.158245,-0.011446,-0.112260,-0.028892
2020-03-18,-0.050633,-0.066507,-0.024480,-0.042096,-0.105268,-0.054140,-0.100244,-0.157443,-0.019922,-0.134006,-0.072296
2020-03-20,-0.043094,-0.033901,-0.063486,-0.037558,-0.021102,-0.072170,-0.049085,0.043261,0.014996,-0.052336,-0.030230
2020-04-01,-0.045005,-0.077883,-0.052617,-0.035508,-0.062979,-0.068771,-0.011588,0.012038,0.009456,0.087951,-0.032317
2020-04-21,-0.030363,-0.061104,-0.030910,-0.041357,-0.029005,-0.038222,-0.005342,-0.016428,-0.006825,-0.244036,-0.053534
2020-06-11,-0.057649,-0.060907,-0.048010,-0.053698,-0.083443,-0.100376,-0.088253,-0.084414,-0.007214,-0.076204,0.018539
2020-09-03,-0.034414,-0.092775,-0.080061,-0.061947,-0.003148,-0.006966,-0.002041,-0.003444,-0.008104,-0.008103,0.000402
2020-10-28,-0.034179,-0.057458,-0.046312,-0.049566,-0.028088,-0.015933,-0.038087,-0.045060,-0.016143,-0.050485,-0.007618
2022-04-29,-0.036956,-0.062430,-0.036605,-0.041812,-0.032268,-0.030698,-0.022362,-0.028015,-0.000113,0.016265,0.051684
2022-05-05,-0.035543,-0.073276,-0.055716,-0.043555,-0.025020,-0.027965,-0.015158,-0.000527,-0.003811,0.006900,0.043731
2022-05-09,-0.032017,-0.092369,-0.033189,-0.036945,-0.015034,-0.028839,-0.078852,-0.058059,-0.014479,-0.057389,-0.126445
2022-05-18,-0.040312,-0.068163,-0.056419,-0.045530,-0.017106,-0.030842,-0.015851,-0.002050,0.000531,-0.025194,0.007707
2022-06-13,-0.037968,-0.078178,-0.038285,-0.042413,-0.029778,-0.034670,-0.045889,-0.035530,-0.026412,0.002131,-0.027232
2022-06-16,-0.033096,-0.056030,-0.039651,-0.026970,-0.017156,-0.006240,-0.036885,-0.046579,0.011243,0.010969,0.005930
2022-08-26,-0.033849,-0.092279,-0.037699,-0.038588,-0.032729,-0.031588,-0.012312,0.002557,-0.012153,0.016610,-0.008427
2022-09-13,-0.043482,-0.094726,-0.058679,-0.054979,-0.034749,-0.036008,-0.023358,-0.014823,-0.013011,-0.008830,0.004243
2025-04-03,-0.049281,-0.078065,-0.092456,-0.023630,-0.069685,-0.110633,-0.052583,-0.040567,-0.006038,-0.064176,0.020469
2025-04-04,-0.058543,-0.073576,-0.072887,-0.035566,-0.074838,-0.076034,-0.071956,-0.080837,-0.023392,-0.065013,-0.072740
2025-04-10,-0.043819,-0.059127,-0.042394,-0.023406,-0.030853,-0.034993,-0.055482,-0.064329,0.024424,-0.032834,-0.067872

In [58]:
# On affiche le nombre de jours de crash, la plus petite / grande date, top 5 rendements les plus faibles

print(len(crash_days))
print(crash_days.index.min().date())
print(crash_days.index.max().date())
crash_days["S&P 500"].nsmallest(5)

46
2010-02-04
2025-04-10

Date
2020-03-16   -0.109424
2020-03-12   -0.095677
2020-03-09   -0.078094
2011-08-08   -0.065123
2025-04-04   -0.058543
Name: S&P 500, dtype: float64

In [59]:
crash_days

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-02-04,-0.030866,-0.058058,-0.036039,-0.027593,-0.048151,-0.050226,-0.028228,-0.040719,-0.039834,-0.049921,-0.000554
2010-05-06,-0.033213,-0.020690,-0.038049,-0.029146,-0.042693,-0.071306,-0.034457,-0.034561,0.029542,-0.033652,-0.015535
2010-05-20,-0.037759,-0.023511,-0.042602,-0.040014,-0.039360,-0.061925,-0.033947,-0.017351,-0.006774,-0.025105,-0.012506
2010-06-04,-0.035137,-0.047244,-0.027212,-0.039836,-0.037852,-0.029096,-0.032976,-0.042175,0.010427,-0.044026,0.022814
2010-06-29,-0.030875,-0.055856,-0.045210,-0.041136,-0.038402,-0.043963,-0.020181,-0.031593,0.001487,-0.027710,-0.035828
2011-08-04,-0.046842,-0.095206,-0.038719,-0.036404,-0.049624,-0.074423,-0.049923,-0.070523,-0.005264,-0.052813,-0.036430
2011-08-08,-0.065123,-0.078764,-0.054627,-0.046729,-0.094149,-0.203182,-0.061882,-0.068168,0.033199,-0.051477,-0.001522
2011-08-10,-0.044177,-0.045630,-0.027593,-0.053949,-0.055769,-0.109210,-0.044120,-0.040357,0.035407,0.040070,0.002253
2011-08-18,-0.043118,-0.067916,-0.037825,-0.022970,-0.037736,-0.060322,-0.043420,-0.036077,0.018920,-0.032640,-0.010425
2011-09-22,-0.032324,-0.066345,-0.025040,-0.035783,-0.035267,-0.050157,-0.037933,-0.023753,-0.026154,-0.044128,-0.006702
2011-11-09,-0.036909,-0.050398,-0.026955,-0.035346,-0.070817,-0.056662,-0.029714,-0.049910,-0.008413,-0.023391,-0.024833
2015-08-21,-0.030102,-0.031137,-0.061163,-0.056724,-0.035487,-0.037082,-0.032721,-0.032294,0.006248,-0.024882,-0.028675
2015-08-24,-0.042107,-0.035398,-0.024962,-0.032273,-0.052673,-0.050310,-0.047276,-0.051678,-0.005399,-0.060933,-0.009716
2016-06-24,-0.035909,-0.056919,-0.028096,-0.040069,-0.069477,-0.074074,-0.026252,-0.064347,0.049038,-0.049106,-0.013343
2018-02-05,-0.041823,-0.084875,-0.024985,-0.041185,-0.047952,-0.052895,-0.056902,-0.041010,0.002532,-0.013998,-0.034786
2018-02-08,-0.037509,-0.049300,-0.027516,-0.051334,-0.044210,-0.048320,-0.011307,-0.022116,0.001523,-0.010685,-0.001850
2018-10-10,-0.031663,-0.074753,-0.046326,-0.054338,-0.026633,-0.024683,-0.023003,-0.020202,0.002487,-0.022471,0.005511
2018-10-24,-0.030298,-0.097938,-0.034302,-0.053469,-0.018622,-0.030718,-0.027805,-0.027888,0.002320,-0.003532,-0.014321
2018-12-04,-0.032402,-0.076041,-0.043989,-0.031849,-0.044637,-0.054310,-0.022039,-0.018597,0.006099,0.006322,0.027195
2019-08-05,-0.030073,-0.064520,-0.052348,-0.034259,-0.029753,-0.044248,-0.020488,-0.022941,0.013982,-0.033608,-0.024045
2020-02-24,-0.033165,-0.070697,-0.047500,-0.043115,-0.026876,-0.047439,-0.046846,-0.038438,0.008985,-0.037607,-0.040945
2020-02-25,-0.030302,-0.041094,-0.033872,-0.016502,-0.044643,-0.050412,-0.038325,-0.029188,-0.017874,-0.023979,0.010947
2020-02-27,-0.044912,-0.055666,-0.065368,-0.070459,-0.041614,-0.048972,-0.060177,-0.039563,0.000195,-0.023395,-0.037891
2020-03-05,-0.033242,-0.039436,-0.032437,-0.025095,-0.049062,-0.050691,-0.044067,-0.034658,0.021601,-0.022296,-0.030104
2020-03-09,-0.078094,-0.077432,-0.079092,-0.067772,-0.135455,-0.147024,-0.122248,-0.171722,0.001650,-0.240998,0.040984
2020-03-11,-0.048749,-0.055960,-0.034730,-0.045302,-0.047070,-0.039813,-0.032942,-0.066829,-0.003560,-0.038420,-0.029959
2020-03-12,-0.095677,-0.122368,-0.098755,-0.094838,-0.082430,-0.095280,-0.114340,-0.149609,-0.039888,-0.071808,-0.019702
2020-03-16,-0.109424,-0.184521,-0.128647,-0.147391,-0.149649,-0.153973,-0.095226,-0.158245,-0.011446,-0.112260,-0.028892
2020-03-18,-0.050633,-0.066507,-0.024480,-0.042096,-0.105268,-0.054140,-0.100244,-0.157443,-0.019922,-0.134006,-0.072296
2020-03-20,-0.043094,-0.033901,-0.063486,-0.037558,-0.021102,-0.072170,-0.049085,0.043261,0.014996,-0.052336,-0.030230
2020-04-01,-0.045005,-0.077883,-0.052617,-0.035508,-0.062979,-0.068771,-0.011588,0.012038,0.009456,0.087951,-0.032317
2020-04-21,-0.030363,-0.061104,-0.030910,-0.041357,-0.029005,-0.038222,-0.005342,-0.016428,-0.006825,-0.244036,-0.053534
2020-06-11,-0.057649,-0.060907,-0.048010,-0.053698,-0.083443,-0.100376,-0.088253,-0.084414,-0.007214,-0.076204,0.018539
2020-09-03,-0.034414,-0.092775,-0.080061,-0.061947,-0.003148,-0.006966,-0.002041,-0.003444,-0.008104,-0.008103,0.000402
2020-10-28,-0.034179,-0.057458,-0.046312,-0.049566,-0.028088,-0.015933,-0.038087,-0.045060,-0.016143,-0.050485,-0.007618
2022-04-29,-0.036956,-0.062430,-0.036605,-0.041812,-0.032268,-0.030698,-0.022362,-0.028015,-0.000113,0.016265,0.051684
2022-05-05,-0.035543,-0.073276,-0.055716,-0.043555,-0.025020,-0.027965,-0.015158,-0.000527,-0.003811,0.006900,0.043731
2022-05-09,-0.032017,-0.092369,-0.033189,-0.036945,-0.015034,-0.028839,-0.078852,-0.058059,-0.014479,-0.057389,-0.126445
2022-05-18,-0.040312,-0.068163,-0.056419,-0.045530,-0.017106,-0.030842,-0.015851,-0.002050,0.000531,-0.025194,0.007707
2022-06-13,-0.037968,-0.078178,-0.038285,-0.042413,-0.029778,-0.034670,-0.045889,-0.035530,-0.026412,0.002131,-0.027232
2022-06-16,-0.033096,-0.056030,-0.039651,-0.026970,-0.017156,-0.006240,-0.036885,-0.046579,0.011243,0.010969,0.005930
2022-08-26,-0.033849,-0.092279,-0.037699,-0.038588,-0.032729,-0.031588,-0.012312,0.002557,-0.012153,0.016610,-0.008427
2022-09-13,-0.043482,-0.094726,-0.058679,-0.054979,-0.034749,-0.036008,-0.023358,-0.014823,-0.013011,-0.008830,0.004243
2025-04-03,-0.049281,-0.078065,-0.092456,-0.023630,-0.069685,-0.110633,-0.052583,-0.040567,-0.006038,-0.064176,0.020469
2025-04-04,-0.058543,-0.073576,-0.072887,-0.035566,-0.074838,-0.076034,-0.071956,-0.080837,-0.023392,-0.065013,-0.072740
2025-04-10,-0.043819,-0.059127,-0.042394,-0.023406,-0.030853,-0.034993,-0.055482,-0.064329,0.024424,-0.032834,-0.067872

In [60]:
# on calcule ensuite coefficients régression

import statsmodels.api as sm

results = []

benchmark = "S&P 500"
for asset in crash_days.columns:

    if asset == benchmark:
        continue

    y = crash_days[asset]
    X = crash_days[benchmark]

    X = sm.add_constant(X)

    model = sm.OLS(y,X).fit()

    results.append(
    {
        "Asset": asset,
        "alpha": model.params["const"],
        "crash_beta":model.params[benchmark],
        "std_error": model.bse[benchmark],
        "t_stat":model.tvalues[benchmark],
        "p_value":model.pvalues[benchmark],
        "r_squared":model.rsquared,
        "n_crash_days":int(model.nobs),
    }
    )

In [61]:
results

[{'Asset': 'Nvidia',
  'alpha': np.float64(-0.022377470531194245),
  'crash_beta': np.float64(1.058645878273572),
  'std_error': np.float64(0.19519124991583217),
  't_stat': np.float64(5.423633891017489),
  'p_value': np.float64(2.353826610669908e-06),
  'r_squared': np.float64(0.4006740067830984),
  'n_crash_days': 46},
 {'Asset': 'Apple',
  'alpha': np.float64(-0.006666951305073143),
  'crash_beta': np.float64(0.9516491342549552),
  'std_error': np.float64(0.1390733543118008),
  't_stat': np.float64(6.842785513904909),
  'p_value': np.float64(1.9440693825580925e-08),
  'r_squared': np.float64(0.515545023858391),
  'n_crash_days': 46},
 {'Asset': 'Microsoft',
  'alpha': np.float64(-0.004075810649681872),
  'crash_beta': np.float64(0.9492957295385414),
  'std_error': np.float64(0.1292054073660153),
  't_stat': np.float64(7.3471826674355825),
  'p_value': np.float64(3.553288190628735e-09),
  'r_squared': np.float64(0.550933771138487),
  'n_crash_days': 46},
 {'Asset': 'JPMorgan',
  'alpha': np.float64(0.014479069066552608),
  'crash_beta': np.float64(1.4650096608802732),
  'std_error': np.float64(0.16035362344135934),
  't_stat': np.float64(9.13611822071499),
  'p_value': np.float64(1.0044361618097989e-11),
  'r_squared': np.float64(0.6548171030321359),
  'n_crash_days': 46},
 {'Asset': 'Bank of America',
  'alpha': np.float64(0.01441433650459058),
  'crash_beta': np.float64(1.6966681365975054),
  'std_error': np.float64(0.24126699369214274),
  't_stat': np.float64(7.032325933328692),
  'p_value': np.float64(1.0250533953300695e-08),
  'r_squared': np.float64(0.5291781566671385),
  'n_crash_days': 46},
 {'Asset': 'Exxon Mobil',
  'alpha': np.float64(0.0115515004437829),
  'crash_beta': np.float64(1.271887187260509),
  'std_error': np.float64(0.16794226814726423),
  't_stat': np.float64(7.573359591316369),
  'p_value': np.float64(1.6660902086381421e-09),
  'r_squared': np.float64(0.5658856164514516),
  'n_crash_days': 46},
 {'Asset': 'Shell',
  'alpha': np.float64(0.0396551410263129),
  'crash_beta': np.float64(1.9821076540864928),
  'std_error': np.float64(0.2621006478048494),
  't_stat': np.float64(7.562391282459928),
  'p_value': np.float64(1.7282829720156379e-09),
  'r_squared': np.float64(0.5651734012423317),
  'n_crash_days': 46},
 {'Asset': 'Gold',
  'alpha': np.float64(0.0082460233071284),
  'crash_beta': np.float64(0.20145335496775807),
  'std_error': np.float64(0.16608243452364488),
  't_stat': np.float64(1.2129720734499319),
  'p_value': np.float64(0.2316126020961081),
  'r_squared': np.float64(0.03235669995122614),
  'n_crash_days': 46},
 {'Asset': 'Oil',
  'alpha': np.float64(0.01984599107110306),
  'crash_beta': np.float64(1.3859050224182798),
  'std_error': np.float64(0.4818150820739472),
  't_stat': np.float64(2.876425155586093),
  'p_value': np.float64(0.00618003058057221),
  'r_squared': np.float64(0.15827849218716072),
  'n_crash_days': 46},
 {'Asset': 'Gas',
  'alpha': np.float64(-0.015000601309027148),
  'crash_beta': np.float64(0.0024666465361874723),
  'std_error': np.float64(0.300445749443738),
  't_stat': np.float64(0.00820995650880187),
  'p_value': np.float64(0.9934865878743195),
  'r_squared': np.float64(1.5318927866214693e-06),
  'n_crash_days': 46}]

In [62]:
crash_betas = pd.DataFrame(results)
crash_betas

,Asset,alpha,crash_beta,std_error,t_stat,p_value,r_squared,n_crash_days
0,Nvidia,-0.022377,1.058646,0.195191,5.423634,2.353827e-06,0.400674,46
1,Apple,-0.006667,0.951649,0.139073,6.842786,1.944069e-08,0.515545,46
2,Microsoft,-0.004076,0.949296,0.129205,7.347183,3.553288e-09,0.550934,46
3,JPMorgan,0.014479,1.465010,0.160354,9.136118,1.004436e-11,0.654817,46
4,Bank of America,0.014414,1.696668,0.241267,7.032326,1.025053e-08,0.529178,46
5,Exxon Mobil,0.011552,1.271887,0.167942,7.573360,1.666090e-09,0.565886,46
6,Shell,0.039655,1.982108,0.262101,7.562391,1.728283e-09,0.565173,46
7,Gold,0.008246,0.201453,0.166082,1.212972,2.316126e-01,0.032357,46
8,Oil,0.019846,1.385905,0.481815,2.876425,6.180031e-03,0.158278,46
9,Gas,-0.015001,0.002467,0.300446,0.008210,9.934866e-01,0.000002,46

In [63]:
#Defining portfolio weight

weight_Nvidia = 0.1
weight_Apple = 0.1
weight_Microsoft = 0.1 
weight_JPMorgan = 0.1
weight_Bank_of_America = 0.1
weight_Exxon_Mobil = 0.1
weight_Shell = 0.1
weight_Gold = 0.1
weight_Oil = 0.1 
weight_Gas = 0.1

s = weight_Nvidia + weight_Apple + weight_Microsoft + weight_JPMorgan + weight_Bank_of_America  + weight_Exxon_Mobil + weight_Shell + weight_Gold + weight_Oil + weight_Gas 
print(s)

0.9999999999999999

In [64]:
list(crash_betas["Asset"])

['Nvidia',
 'Apple',
 'Microsoft',
 'JPMorgan',
 'Bank of America',
 'Exxon Mobil',
 'Shell',
 'Gold',
 'Oil',
 'Gas']

In [65]:
dico = {
    "Asset":list(crash_betas["Asset"]),
    "Weight":[weight_Nvidia,
            weight_Apple, 
                weight_Microsoft,
                weight_JPMorgan,
                weight_Bank_of_America,
                weight_Exxon_Mobil, 
                weight_Shell,
                weight_Gold,
                weight_Oil,
                weight_Gas ]
}

In [66]:
weight = pd.DataFrame(dico)
weight

             Asset  Weight
0           Nvidia     0.1
1            Apple     0.1
2        Microsoft     0.1
3         JPMorgan     0.1
4  Bank of America     0.1
5      Exxon Mobil     0.1
6            Shell     0.1
7             Gold     0.1
8              Oil     0.1
9              Gas     0.1

In [67]:
portfolio = crash_betas[["Asset","crash_beta"]]
portfolio

             Asset  crash_beta
0           Nvidia    1.058646
1            Apple    0.951649
2        Microsoft    0.949296
3         JPMorgan    1.465010
4  Bank of America    1.696668
5      Exxon Mobil    1.271887
6            Shell    1.982108
7             Gold    0.201453
8              Oil    1.385905
9              Gas    0.002467

In [68]:
portfolio = pd.merge(portfolio,weight,left_on="Asset",right_on = "Asset")
portfolio

             Asset  crash_beta  Weight
0           Nvidia    1.058646     0.1
1            Apple    0.951649     0.1
2        Microsoft    0.949296     0.1
3         JPMorgan    1.465010     0.1
4  Bank of America    1.696668     0.1
5      Exxon Mobil    1.271887     0.1
6            Shell    1.982108     0.1
7             Gold    0.201453     0.1
8              Oil    1.385905     0.1
9              Gas    0.002467     0.1

In [69]:
data.iloc[-1] # une series

Ticker
S&P 500            762.396790
Nvidia             218.289993
Apple              332.269989
Microsoft          495.630005
JPMorgan           356.230011
Bank of America     62.689999
Exxon Mobil        165.990005
Shell               96.769997
Gold               398.769989
Oil                104.610001
Gas                  2.831000
Name: 2026-09-11 00:00:00, dtype: float64

In [70]:
spot_price = data.tail(1) # un dataframe
spot_price

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2026-09-11,762.39679,218.289993,332.269989,495.630005,356.230011,62.689999,165.990005,96.769997,398.769989,104.610001,2.831

In [71]:
spot_price = data.tail(1).transpose()  # un dataframe
spot_price

Date             2026-09-11
Ticker
S&P 500          762.396790
Nvidia           218.289993
Apple            332.269989
Microsoft        495.630005
JPMorgan         356.230011
Bank of America   62.689999
Exxon Mobil      165.990005
Shell             96.769997
Gold             398.769989
Oil              104.610001
Gas                2.831000

In [72]:
portfolio = pd.merge(portfolio,spot_price,left_on="Asset",right_on="Ticker")
portfolio

             Asset  crash_beta  Weight  2026-09-11 00:00:00
0           Nvidia    1.058646     0.1           218.289993
1            Apple    0.951649     0.1           332.269989
2        Microsoft    0.949296     0.1           495.630005
3         JPMorgan    1.465010     0.1           356.230011
4  Bank of America    1.696668     0.1            62.689999
5      Exxon Mobil    1.271887     0.1           165.990005
6            Shell    1.982108     0.1            96.769997
7             Gold    0.201453     0.1           398.769989
8              Oil    1.385905     0.1           104.610001
9              Gas    0.002467     0.1             2.831000

In [73]:
portfolio.columns
L=list(portfolio.columns)
L

['Asset', 'crash_beta', 'Weight', Timestamp('2026-09-11 00:00:00')]

In [74]:
Initial_capital = 1_000_000 
#portfolio["Position Value $"] = Initial_capital * portfolio["Weight"] * portfolio[L[-1]]
portfolio["Position Value $"] = Initial_capital * portfolio["Weight"] 
portfolio
print(sum(portfolio["Position Value $"]))
portfolio

1000000.0

             Asset  crash_beta  Weight  2026-09-11 00:00:00  Position Value $
0           Nvidia    1.058646     0.1           218.289993          100000.0
1            Apple    0.951649     0.1           332.269989          100000.0
2        Microsoft    0.949296     0.1           495.630005          100000.0
3         JPMorgan    1.465010     0.1           356.230011          100000.0
4  Bank of America    1.696668     0.1            62.689999          100000.0
5      Exxon Mobil    1.271887     0.1           165.990005          100000.0
6            Shell    1.982108     0.1            96.769997          100000.0
7             Gold    0.201453     0.1           398.769989          100000.0
8              Oil    1.385905     0.1           104.610001          100000.0
9              Gas    0.002467     0.1             2.831000          100000.0

In [75]:
portfolio["Asset Volume"] = portfolio["Position Value $"]/portfolio[L[-1]]
portfolio

,Asset,crash_beta,Weight,2026-09-11 00:00:00,Position Value $,Asset Volume
0,Nvidia,1.058646,0.1,218.289993,100000.0,458.106203
1,Apple,0.951649,0.1,332.269989,100000.0,300.960073
2,Microsoft,0.949296,0.1,495.630005,100000.0,201.763410
3,JPMorgan,1.465010,0.1,356.230011,100000.0,280.717505
4,Bank of America,1.696668,0.1,62.689999,100000.0,1595.150777
5,Exxon Mobil,1.271887,0.1,165.990005,100000.0,602.445911
6,Shell,1.982108,0.1,96.769997,100000.0,1033.378149
7,Gold,0.201453,0.1,398.769989,100000.0,250.771128
8,Oil,1.385905,0.1,104.610001,100000.0,955.931550
9,Gas,0.002467,0.1,2.831000,100000.0,35323.206229

In [76]:
portfolio.rename(columns={L[-1]:"Spot Price $"},inplace=True)
portfolio

,Asset,crash_beta,Weight,Spot Price $,Position Value $,Asset Volume
0,Nvidia,1.058646,0.1,218.289993,100000.0,458.106203
1,Apple,0.951649,0.1,332.269989,100000.0,300.960073
2,Microsoft,0.949296,0.1,495.630005,100000.0,201.763410
3,JPMorgan,1.465010,0.1,356.230011,100000.0,280.717505
4,Bank of America,1.696668,0.1,62.689999,100000.0,1595.150777
5,Exxon Mobil,1.271887,0.1,165.990005,100000.0,602.445911
6,Shell,1.982108,0.1,96.769997,100000.0,1033.378149
7,Gold,0.201453,0.1,398.769989,100000.0,250.771128
8,Oil,1.385905,0.1,104.610001,100000.0,955.931550
9,Gas,0.002467,0.1,2.831000,100000.0,35323.206229

In [78]:
Shock = [-0.05,-0.1,-0.2,-0.3,-0.4]

dico = {
    "S&P500 Shock":Shock,   
}

stress_results = pd.DataFrame(dico)
stress_results

   S&P500 Shock
0         -0.05
1         -0.10
2         -0.20
3         -0.30
4         -0.40

In [80]:
for _, row in portfolio.iterrows():

    asset = row["Asset"]
    beta = row["crash_beta"]

    stressed_return = beta * stress_results["S&P500 Shock"]

    pnl = row["Position Value $"] * stressed_return

    stress_results[f"{asset} Stressed Return"] = stressed_return
    stress_results[f"{asset} PnL"] = pnl


stress_results

,S&P500 Shock,Nvidia Stressed Return,Nvidia PnL,Apple Stressed Return,Apple PnL,Microsoft Stressed Return,Microsoft PnL,JPMorgan Stressed Return,JPMorgan PnL,Bank of America Stressed Return,...,Exxon Mobil Stressed Return,Exxon Mobil PnL,Shell Stressed Return,Shell PnL,Gold Stressed Return,Gold PnL,Oil Stressed Return,Oil PnL,Gas Stressed Return,Gas PnL
0,-0.05,-0.052932,-5293.229391,-0.047582,-4758.245671,-0.047465,-4746.478648,-0.073250,-7325.048304,-0.084833,...,-0.063594,-6359.435936,-0.099105,-9910.538270,-0.010073,-1007.266775,-0.069295,-6929.525112,-0.000123,-12.333233
1,-0.10,-0.105865,-10586.458783,-0.095165,-9516.491343,-0.094930,-9492.957295,-0.146501,-14650.096609,-0.169667,...,-0.127189,-12718.871873,-0.198211,-19821.076541,-0.020145,-2014.533550,-0.138591,-13859.050224,-0.000247,-24.666465
2,-0.20,-0.211729,-21172.917565,-0.190330,-19032.982685,-0.189859,-18985.914591,-0.293002,-29300.193218,-0.339334,...,-0.254377,-25437.743745,-0.396422,-39642.153082,-0.040291,-4029.067099,-0.277181,-27718.100448,-0.000493,-49.332931
3,-0.30,-0.317594,-31759.376348,-0.285495,-28549.474028,-0.284789,-28478.871886,-0.439503,-43950.289826,-0.509000,...,-0.381566,-38156.615618,-0.594632,-59463.229623,-0.060436,-6043.600649,-0.415772,-41577.150673,-0.000740,-73.999396
4,-0.40,-0.423458,-42345.835131,-0.380660,-38065.965370,-0.379718,-37971.829182,-0.586004,-58600.386435,-0.678667,...,-0.508755,-50875.487490,-0.792843,-79284.306163,-0.080581,-8058.134199,-0.554362,-55436.200897,-0.000987,-98.665861

In [81]:
L=[]
for name in stress_results.columns:
    if "PnL" in name:
        L.append(name)
print(L)

['Nvidia PnL', 'Apple PnL', 'Microsoft PnL', 'JPMorgan PnL', 'Bank of America PnL', 'Exxon Mobil PnL', 'Shell PnL', 'Gold PnL', 'Oil PnL', 'Gas PnL']

In [83]:
stress_results["Portfolio P&L $"] = stress_results[L].sum(axis=1) # somme sur chaque ligne
stress_results

,S&P500 Shock,Nvidia Stressed Return,Nvidia PnL,Apple Stressed Return,Apple PnL,Microsoft Stressed Return,Microsoft PnL,JPMorgan Stressed Return,JPMorgan PnL,Bank of America Stressed Return,...,Exxon Mobil PnL,Shell Stressed Return,Shell PnL,Gold Stressed Return,Gold PnL,Oil Stressed Return,Oil PnL,Gas Stressed Return,Gas PnL,Portfolio P&L $
0,-0.05,-0.052932,-5293.229391,-0.047582,-4758.245671,-0.047465,-4746.478648,-0.073250,-7325.048304,-0.084833,...,-6359.435936,-0.099105,-9910.538270,-0.010073,-1007.266775,-0.069295,-6929.525112,-0.000123,-12.333233,-54825.442024
1,-0.10,-0.105865,-10586.458783,-0.095165,-9516.491343,-0.094930,-9492.957295,-0.146501,-14650.096609,-0.169667,...,-12718.871873,-0.198211,-19821.076541,-0.020145,-2014.533550,-0.138591,-13859.050224,-0.000247,-24.666465,-109650.884048
2,-0.20,-0.211729,-21172.917565,-0.190330,-19032.982685,-0.189859,-18985.914591,-0.293002,-29300.193218,-0.339334,...,-25437.743745,-0.396422,-39642.153082,-0.040291,-4029.067099,-0.277181,-27718.100448,-0.000493,-49.332931,-219301.768096
3,-0.30,-0.317594,-31759.376348,-0.285495,-28549.474028,-0.284789,-28478.871886,-0.439503,-43950.289826,-0.509000,...,-38156.615618,-0.594632,-59463.229623,-0.060436,-6043.600649,-0.415772,-41577.150673,-0.000740,-73.999396,-328952.652144
4,-0.40,-0.423458,-42345.835131,-0.380660,-38065.965370,-0.379718,-37971.829182,-0.586004,-58600.386435,-0.678667,...,-50875.487490,-0.792843,-79284.306163,-0.080581,-8058.134199,-0.554362,-55436.200897,-0.000987,-98.665861,-438603.536193

In [87]:
stress_results["Portfolio Return"] = stress_results["Portfolio P&L $"]/Initial_capital
stress_results
stress_results.round(4)

,S&P500 Shock,Nvidia Stressed Return,Nvidia PnL,Apple Stressed Return,Apple PnL,Microsoft Stressed Return,Microsoft PnL,JPMorgan Stressed Return,JPMorgan PnL,Bank of America Stressed Return,...,Shell Stressed Return,Shell PnL,Gold Stressed Return,Gold PnL,Oil Stressed Return,Oil PnL,Gas Stressed Return,Gas PnL,Portfolio P&L $,Portfolio Return
0,-0.05,-0.0529,-5293.2294,-0.0476,-4758.2457,-0.0475,-4746.4786,-0.0733,-7325.0483,-0.0848,...,-0.0991,-9910.5383,-0.0101,-1007.2668,-0.0693,-6929.5251,-0.0001,-12.3332,-54825.4420,-0.0548
1,-0.10,-0.1059,-10586.4588,-0.0952,-9516.4913,-0.0949,-9492.9573,-0.1465,-14650.0966,-0.1697,...,-0.1982,-19821.0765,-0.0201,-2014.5335,-0.1386,-13859.0502,-0.0002,-24.6665,-109650.8840,-0.1097
2,-0.20,-0.2117,-21172.9176,-0.1903,-19032.9827,-0.1899,-18985.9146,-0.2930,-29300.1932,-0.3393,...,-0.3964,-39642.1531,-0.0403,-4029.0671,-0.2772,-27718.1004,-0.0005,-49.3329,-219301.7681,-0.2193
3,-0.30,-0.3176,-31759.3763,-0.2855,-28549.4740,-0.2848,-28478.8719,-0.4395,-43950.2898,-0.5090,...,-0.5946,-59463.2296,-0.0604,-6043.6006,-0.4158,-41577.1507,-0.0007,-73.9994,-328952.6521,-0.3290
4,-0.40,-0.4235,-42345.8351,-0.3807,-38065.9654,-0.3797,-37971.8292,-0.5860,-58600.3864,-0.6787,...,-0.7928,-79284.3062,-0.0806,-8058.1342,-0.5544,-55436.2009,-0.0010,-98.6659,-438603.5362,-0.4386